apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      color: blue
  template:
    metadata:
      labels:
        app: myapp
        color: blue
    spec:
      containers:
        - name: myapp
          image: mydockerhubuser/myapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: COLOR
              value: "blue"
